---
- name: run optional versionscheck
  ansible.builtin.include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: install nextcloud-client
  ansible.builtin.package:
    name:
    - nextcloud-client
    - gnome-keyring
    - libsecret
    - tmux
    state: present
  become: true

- name: create nextcloud tmux launcher
  ansible.builtin.template:
    src: templates/nextcloud-client-launcher.sh.j2
    dest: /usr/local/bin/launch-nextcloud-client.sh
    mode: 0755
    owner: root
  become: true
  when: run_systemd | bool

- name: install nextcloud systemd unit file
  ansible.builtin.template:
    src: templates/nextcloud.j2
    dest: /etc/systemd/system/nextcloud.service
  become: true
  when: run_systemd | bool

- name: start nextcloud client
  ansible.builtin.systemd:
    state: restarted
    name: nextcloud
    daemon_reload: true
  become: true
  when: run_systemd | bool

- name: enable nextcloud client
  ansible.builtin.systemd:
    enabled: true
    name: nextcloud
  become: true
  when: run_systemd | bool
