---

- name: install nextcloud-client
  package:
    name:
    - nextcloud-client
    - gnome-keyring
    - libsecret
    - tmux
    state: present
  become: yes

- name: create nextcloud tmux launcher
  template:
    src: templates/nextcloud-client-launcher.sh.j2
    dest: /usr/local/bin/launch-nextcloud-client.sh
    mode: 0755
    owner: root
  become: yes
  when: run_systemd

- name: install nextcloud systemd unit file
  template:
    src: templates/nextcloud.j2
    dest: /etc/systemd/system/nextcloud.service
  become: yes
  when: run_systemd

- name: start nextcloud client
  systemd: 
    state: restarted
    name: nextcloud
    daemon_reload: yes
  become: yes
  when: run_systemd

- name: enable nextcloud client
  systemd: 
    enabled: yes
    name: nextcloud
  become: yes
  when: run_systemd


